### ISSUE TITLE
PaNOSC on Cordis

### ISSUE THREAD

**Issue by andygotz** [panosc-eu/panosc#18]
PaNOSC needs to be declared on the Cordis site: https://cordis.europa.eu/home_en.html

This is part of the Outreach activities so could CERIC look after this please?

Thanks in advance

**Comment by darioceric** [comment]
Dear All, 
we will take care of this. As soon as possibile i will let you know. 
Thank you.
Dario

**Comment by NicolettaCarboni** [comment]
I called the CORDIS help desk to retrieve some info. The project information on CORDIS is automatically taken from the EC's internal systems (i.e. the participant portal). They told me that, since the project has just started, it may take some days before such info is updated. We'll then be able to use all services offered by CORDIS for the promotion of project's activities and results.

**Comment by NicolettaCarboni** [comment]
Probably the info on the participant portal (i.e. abstract and activity) should be updated to have it then on Cordis

**Comment by NicolettaCarboni** [comment]
PaNOSC is now on CORDIS: https://cordis.europa.eu/project/rcn/219175_en.html

**Comment by andygotz** [comment]
Good news! Thanks for following this up. I will close this issue.
