### ISSUE TITLE
Joint Annual meeting PaNOSC/ExPaNDS

### ISSUE THREAD

**Issue by JBodera** [panosc-eu/panosc#53]
It has been agreed that a joint PaNOSC/ExPaNDS annual meeting is desirable and a possible range of dates suggested: 19/10/2020 to 01/11/2020.

As per [PMC 29/01/2019](https://github.com/panosc-eu/panosc/tree/master/Work%20Packages/WP1%20Management/Meetings/Project%20Management%20Committee):
* The expected duration of the event is 4 days
* It would be good if the event could start with lunch, rather than during the morning
* Expected number of attendees is around 100
* ELI could host the event

It is required to 
**1. Confirm exact dates**
**2. Confirm maximum number of attendees**

**Comment by JBodera** [comment]
This is a summary of the meetings / conversations that have been taking place so far regarding the joint annual meeting:


# 5th call (06.04.2020)
Thanks for today's meeting, here is the summarised record:
- 'Talk 1' would be even more interesting as a 1-hour panel discussion on EOSC with Jan Hrusak, Rupert Lück and 2-3 others panelists.
> Action: think about other panelists and fill the shared doc (https://syncandshare.desy.de/index.php/s/3c6cREQkTk9E8KE)

- Which leaves time for only 1 other talk then for 30/45 min: the favorite so far is Susanna Sansone.
> Action: each of us investigate and if there is no objection we invite her as soon as we have an Indico page.

- Indico page to be set up by Florian and Renata in consultation with Nicoletta and Kat. Objective: by mid-April.
- Plenary sessions should be organised so people can participate remotely (incl. speaker) - see https://www.owllabs.com/meeting-owl.
- The ExPaNDS CB meeting can be held on Wednesday. Sophie will confirm when planned with CB.

We didn't agree on a next meeting, I think we can aim for a next checkpoint at the end of W17?

# 4th call (23.03.2020)
Following our talk with Nicoletta, Florian and Patrick, we agreed on the following:
We have between 1h30 and 2h for the external talks so we can look for 3 speakers max. We'll short-list those speakers with these 3 different perspectives in mind:  
__1. Insider view on EOSC (so Jan Hrušák)  
2. Showcasing a success-story on FAIR from a scientific point of view, something really concrete and by a scientist  
3. Visionary talk from an expert, preferably not European__

Here's the link to the shared document we'll use to further investigate the different speakers identified so far:  
https://syncandshare.desy.de/index.php/s/3c6cREQkTk9E8KE  
(to open in onlyoffice so we can keep it a collaborative file)

We also agreed on keeping the other session of Monday pm high level, with an __overview by the 2 coordinators and a focus on some achievements by the technical coordinator or relevant experts, but no systematic WP presentation__.

# 3rd call (04.03.2020)
Here is a quick summary, please comment if needed:
- The dates are set: 9-11/11.
- The draft agenda is shaping:

First day: 09.11.2020
- before 11am: Side visits for early comers
- 11am: Welcome - registration
- 1pm - 3pm: 1st session: overview of both projects
- 3pm - 5pm: 2nd session: other relevant initiative or subject with guest speaker
- ~~5pm - 6pm: potential closed board meetings~~ closed board meetings: Monday morning, Tuesday after WP, Wednesday early afternoon
- Evening: Working dinner in city center

Second day: 10.11.2020
- 9am-6pm: WP sessions to be discussed with WP leaders (we still have time)

Third day: 11.11.2020
- 9am - ~11am: 1st wrap-up session
- 11am - 12.30pm: 2nd wrap-up session
- afternoon: side visits for late "leavers"

A first draft programme will be distributed by Florian/Renata in the following weeks.

- Concerning the budget, we'd share the costs as a % of the participants. The ExPaNDS part is to be invoiced to DESY (annual meeting = in WP1 DoW). NB: Travel expenses taken by each partner. First estimate to be drafted soon and specific meeting between ELI and DESY to follow.
> Next steps, actions:
>  - ~~Announcement to the participants (internal for now): to be made by the end of March, we agree on it on 23.03.2020 at 10am CET.~~
>  - ~~Think about a relevant speaker (as mentioned before, if possible relating to a particular EOSC deliverable or milestone) and suggest a list (2 projects, by mid April)~~
>  - Who do we want to attract locally (Czech Republic, Germany)? as contributor or better as user (2 projects, by mid April)
>  - Prepare concrete achievements to show off (for PaNOSC cf. demonstrators presented during mid-term review)

# 2nd call (Feb 2020)
We agreed on the following:
- PaNOSC/ExPaNDS all-hands annual meeting will hold in November, 9th noon to 11th noon
- 9.11 pm will be a joint plenary probably with the intervention of a guest = in the ELI big conference room with 120-150 people capacity
- 10.11 am-pm will be the WP working day, a priori without cross-meetings (unless an opportunity for a specific cross-meeting with high added-value is foreseen by one of the WP leads) = 6 rooms @ELI and HILASE
- 11.11 am will be a joint wrap-up session of the work achieved during the meeting and the foreseeable work for the 6 next months = in the ELI big conference room

Florian explained that:
- the working dinner would be on the evening of the 9.11 so the guest speaker could also attend
- there would be a room for management board meetings if necessary (Executive Board for PaNOSC, Collaboration Board for ExPaNDS)
- 50 accommodation rooms are available on-site + the remainder could stay at Continental hotel and ELI could arrange shuttle bus (the rooms are already pre-booked)

> Actions:
> - ~~Think of a guest that would agree to come and give a presentation on an EOSC related deliverable/milestone (all)~~
> - ~~Check with French partners that they saw that the 11.11 was during the planned dates by next Tuesday (Sophie)~~
> - ~~Confirm date and format with all WP leaders by next Wednesday (Andy and Patrick)~~
> - Come up with a first budget estimate (Florian and Renata)

**Comment by servansod** [comment]
Summary of the following meetings:

# 6th call (23.04.2020)
Here are the few notes from our earlier meeting, please comment whenever needed:

- Florian and Renata explained the assumptions behind the tentative budget, with which all agreed so far. The remaining costs to include are rooms and lounge to be charged by ELI beamlines (not much, if any) + investments for owls for the WP meetings to be accessible remotely. For the remote plenary, Kat offered to use the __ExPaNDS Zoom webinar licence__ (up to 500 people), ELI will test the configuration in due time to check it works well with the audio material in the conference room (with microphone for questions in public for remote people to hear etc).

- On the draft programme, it was agreed that the concrete achievements from both projects instead of being presented during the plenary could be made available as __"hands-on" access in the lounge__ during the 3 days. Also, the overview of both projects is to be oriented to the __future user's perspective__ as much as possible. Indeed, it would help attract users from __ELI__, maybe __HZDR__ and possibly others if we are serious enough with __remote access__ (and disseminate accordingly). On the panel session on EOSC we still need to find another panelist. The topic and/or direction of the talk have to be discussed beforehand with the panelists.
> - ~~Sophie to ask Mirjam if she can recommend someone from the sustainability WG.~~ No
> - ~~Andy to ask Rupert if he is available and happy to participate.~~ Yes 
> - ~~Florian and Renata to update the programme accordingly.~~

- The draft indico page is also available [here](https://indico.eli-beams.eu/event/369/page/0).
> - ~~all to have a look and give feedback to Florian and Renata.~~

- Florian also inquired on a space to share the documents (budget maybe not suitable for GitHub), Kat offered to use Sharepoint.
> ~~Kat to set up PaNOSC channel on SharePoint.~~ Nicoletta set up a shared folder


# 7th call (25.05.2020)
- We discussed the objectives and format of the first half-day.
  - We confirmed that the ambition is to put the emphasis on the __user perspective__ (What are both PaNOSC and ExPaNDS going to deliver to users? What is EOSC bringing to users? What is the added value of being FAIR for user communities?).
  - We agreed that we should try to aim at having scientists and users attending. This involves scientific staff of our partner organisations (to the extent possible given travel constraints). We also mentioned reaching out to representatives of user organisations as a way of getting the views and interests of users represented.
  - We considered various configurations for the meeting: only on-site attendance, limited remote participation, large remote participation. We agreed that, to get to have user representation for half a day only, some remote participation should be considered. This would have to be prepared to ensure both technical reliability and quality interaction. We mentioned a number of requirements in relation to the latter aspect: the use of a dedicated app to collect inputs from remote participants; a moderator to ensure interaction between the panelists / speakers and remote participants; (optionally) an online questionnaire ahead of the event to collect input and questions.
- Considering the evolving constraints linked to the pandemic, we agreed on the following approach:
  - We will re-open the Indico page and advertise the programme ASAP
  - We will open registration, but indicate that the meeting (and its format) will only be confirmed __end of August__.
- Regarding the speakers:
  - Rupert Lueck has confirmed his availability
  > - ~~Brian Matthews will be asked to approach and invite Susanna Sansone~~
  > - ~~Isabelle will draft a formal letter of invitation to be sent to the speakers.~~

# 8th call (08.06.2020)

The Clara Futura Hotel is likely to still be closed by the time of the annual meeting. Hotels in Prague will have to be considered instead.
Our short-term objective is to publish the Indico page with the latest version of the programme and open registration.
The webpage will clearly indicate that participation in the first half-day can be on-site or remote and that the final decision on the on-site option will be made at the end of Summer. It should be clear from the announcement that the event WILL take place anyway.
We reviewed the __programme__ and agreed on the changes captured in the attached version. This includes:
- Opening session: EC representative (TBC) added to the opening speeches and timing extended
- First session on PaNOSC and ExPaNDS: names of speakers added and timing updated
- Second session on EOSC: title, list of speakers and timing updated
- Third session on FAIR: timing updated, list of speakers to be updated (agreement on trying to have in priority speakers related directly or indirectly to the PaN community)
- Bus transfer added
- Social dinner renamed "working dinner" :-)
- Tasks:
> - ~~Renata and Florian to update webpage (disclaimer on August milestone, addition of programme and registration form)~~
> - ~~Isabelle to draft letter of invitation for speakers~~
> - ~~Patrick and Sophie to discuss speakers for FAIR session internally (Susan Daenke in particular)~~
> - ~~Andy to get in touch with John Halliwell~~
> - ~~Kat and Nicoletta to work on announcements for social media and emailing~~ (keeping in mind we want to advertise the first half-day event separately from the annual meeting itself).


# 9th call (15.06.2020)

- About the format, we agreed, for clarity, to split the Indico into 2 events, the first day: open, called __'European PaN symposium'__, the second and third days: the 'closed' ExPaNDS-PaNOSC annual all-hands meeting.

- About speakers:
__Tiziana Ferrari__ confirmed she would be happy to give a talk on EOSC-hub and be part of the EOSC panel discussion to follow.
__Susan Daenke__ also accepted Brian's invitation for a talk on FAIR and EOSC-Life.
A second speaker for FAIR, __Filipe Maia__ would apparenty be very good and will be contacted by Florian. If he cannot attend, as a 'back-up' Andy suggested he would then contact __Simon Coles__ (not bad for a back-up). Each FAIR speaker would have ~20 min.
Finally, Patrick will ask __Christian Cucciniello__, our PO, if he can give a 20-minute EC talk during the introduction and also participate in the panel discussion on EOSC.

- We agreed attending the EGI conference one week before was a good thing but that in terms of communication we would need to be careful not to confuse people.

- For the release newspiece of the Indico pages, Nicoletta and Kat will agree on a short text before Thursday EOB. The draft letter to the speakers is ready and will be sent by Kat to us very soon (tomorrow or Wed.).

- Florian and Renata confirmed a hotel in Prague was pre-booked for all attendees, with a 35 days notice to cancel (compatible with our end of August decision day).

# 10th call (26.06.2020)
1. Invitation letter to speakers
 > - ~~Patrick and Andy send their signature to Kat~~
 > - ~~Kat makes the different pdf versions with signature for each speaker and sends to Florian for final check~~
 > - Kat sends the letters (per email) to all speakers, with Renata in cc.
 > - Renata will follow up with the speakers ~~to discuss their travel and accommodation requirements, if any~~.
Deadline: next 2-3 weeks is fine

2. Registration pages
- https://indico.eli-beams.eu/event/376/ and https://indico.eli-beams.eu/event/369/
> - ~~Renata to change the name of the symposium to 'Photon and Neutron EOSC Symposium'~~
> - ~~Nicoletta to send the photo consent form from last year's PaNOSC annual meeting to Florian and Renata~~
> - ~~Renata to add the form + change the options for "in person / remotely" to "in person if possible, remotely otherwise / remotely only"~~
> - ~~All to check both pages and suggest changes before 1st of July~~

3. Promotional letters
> - ~~All to check the final version Nicoletta sent before 1st of July~~

4. when 2 and 3 ok, Dissemination!
 - LEAPS & LEAPS-IT: Andy
 - LENS: Nicoletta
 - EOSCsecretariat: Sophie
 - XFEL user office mailing list: Florian
- LaserLab Europe: Florian
- ESFRI: Florian
- Wayforlight: Florian
- Calispo Plus: Florian
 - Light sources communicators: Kat
 - ExPaNDS partners (incl. EGI) + twitter + webpage: Kat
 - PaNOSC partners + twitter + webpage: Nicoletta

5. Start thinking about WP-day within each project

**Comment by servansod** [comment]
# 11th call (13.07.2020)

## Indico pages

- Florian asked for help with the text of the second paragraph (The Photon and Neutron user communities are diverse and wide-ranging in their requirements. However, both require mapping of experimental data to…) on the Welcome page of European Photon and Neutron Symposium. The text should be focused on the goal of the symposium and on the collaboration of the two projects + should mention numbers of the grant agreements.
- Florian will review more in detail the rest of the text, also the registration page and the clauses regarding the consent with the video recording/ photography on both indico pages.
- All to check both pages and to suggest changes - Andy, Kat should have modification rights to both indico pages, if anyone else wishes to modify the text, they should email Renata who will edit accordingly.

## Invitation letter to speakers

> - ~~Florian to send email address of Jan Hrušák to Kat, Andy shall sent Kat email addresses of  Rupert Lueck (she has already Susan Daenke's)~~
> - ~~Florian to contact Filipe Maia again, second speaker for FAIR, to see whether he could take part~~
> - Both POs of both projects should be formally invited – personalised pdf letter by Kat
> - ~~Kat will finalize the different pdf versions with signatures for each speaker and send them to Florian for final check~~
> - Kat will send the letters (per email) to all speakers, with Renata in cc.
> - Renata will follow up with the speakers to discuss their travel and accommodation requirements, if any.

## Promotional letter

> - ~~All to review Nicoletta’s promotional letter – Florian will send his comments together with the suggestions of the Indico’s welcome page~~


## Symposium programme

- Requirements for the first session “ExPaNDS and PaNOSC: perspectives for future services to users”: Patrick and Andy to meet and to think about the structure – strong emphasis of the session on the users benefits
- Requirements of the panel session:
  - Need to identify key questions/topics to be shared ahead of the symposium that will provide structure to the panel discussion
  - The key questions/topics could already be communicated to the registrants ahead of the event to prepare the discussion
  - Nicoletta will have a look at various tools to manage the collection of questions, e.g. SLIDO, Zoom, etc.
  - Kat has volunteered to organise a short webinar on the use of ZOOM for Nicoletta and Sophie.

## Programme of annual meeting

- Structure of the second and last day of the event: Florian / Sophie will work together on a message to WP leaders, informing them about the format of the meeting and boundary conditions, and ask them for their requirements on how to structure their WP meetings and what cross-WP meeting they would like.
- On the Wednesday morning session, WP leaders will be expected to provide a short summary of each WP (presentation), which should not be a summary of the grant agreement but really cover what was discussed the previous day. They should be all informed in advance.

## Collaboration agreement between DESY and ELI

> - ~~Florian will send a draft to Sophie~~

**Comment by servansod** [comment]
# 12th call (21.08.2020)
## The new structure of the annual meeting
Given the first answers to the survey on travel preferences (60% saying they wouldn't travel even if it is formally allowed out of 26 responses) and the current situation, it has been agreed that the event will be organized as an __online event only__, symposium and internal annual meeting alike.

Considering this, the 2nd day which was intended for internal WP meetings can be left for each WP leader to decide when and with whom it should be held. This WP session is thus taken out of the event _per se_. The so-called 'wrap-up session' becomes then the central session of the internal all-hands meeting, with everyone presenting their achievements and roadmap to everyone else. To make it easier to follow online, we decided to spread this over 2 days. The updated agenda would then be:

    9/11 pm – Symposium: same plan as before
    10/11 am – WP status and roadmap (1/2): min 1 presentation per WP (can be co-presented with sister-WP), max 2.5 hours incl. breaks
    11/11 am – WP status and roadmap (2/2): max 2.5 hours incl. breaks

## Indico pages
> - ~~Renata to update the program to reflect the change of the format of the event, Kat to help adapt the messages.~~

Once updated, the registration link should be disseminated and people be encouraged to register already. Argument to motivate people: the registrants will be contacted before the event to prepare the EOSC session so last minute registrants will not be able to have their say. Plus, the number of registrants will not be limited but if we're more than 300, the last registrants will only have access to the live broadcast.

## Letter to speakers
> - The change of the meeting format needs to be communicated to the invited speakers (Kat and Florian).

## Announcements
> - ~~The announcements shall be adjusted to the new format and the last version checked (Kat).~~

## Costs shared between DESY and ELI
As no extra costs, apart from a potential online conferencing tool (which will disappear if we agree on Zoom), are foreseen, the agreement about the cost sharing between DESY and ELI is no longer necessary.

**Comment by servansod** [comment]
# 31.08.2020 call

With Andy, Patrick, Renata and Sophie we rapidly discussed and finally decided to **join the 2 Indico pages** to make things easier (for everyone except Renata!). 

The 1st day's sessions will get a 'PUBLIC SESSION' label and the 2nd and 3rd days sessions will get an 'INTERNAL SESSION' label. The registration page will have 2 options: first day only or all three days.

As soon as we all agree on the changes (Renata and Andy will work on the page today) we can start the promotion, as discussed earlier. 

Next call will be on the **21.09.2020 at 11am CEST** In the ExPaNDS room. Hopefully we'll have promoted the event by then and sent the letters to speakers so we can start discussing the content of the first day, starting with the coordinator's session.

**Comment by servansod** [comment]
# 21.09.2020 call
## Connection details/live streaming
- It has been agreed that the connection details will be sent only to registered participants.
- Broadcasting the meeting in Youtube will only be possible once the Zoom meeting is launched. The live streaming page URL can be put in the Indico page or our websites or twitter accounts, all of which we can promote in advance.
- A common Youtube channel could also be set up for the occasion. 
> This is to be discussed separately within comm teams.

## User meeting program: “WP status and roadmap” – day 2 and day 3
It was agreed that:
- WP leaders must now be involved in the preparation of these sessions and the Indico agenda should be refined soon, mentioning the WPs and the speakers.
- each session would last 40 min: 20 minutes for achievements, interactions, roadmap + 20 minutes for discussion
- each WP would present with its partner WP:

|Session|PaNOSC WP|ExPaNDS WP|
|-|-|-|
|1|WP1|WP1
|2|WP2|WP2
|3|WP3|WP3
|4|WP4|WP4
|5|WP5|N/A
|6|WP6|WP1/Patrick
|7|WP7|WP1
|8|WP8|WP5
|9|WP9|WP6

*NB: order of the sessions still TBD.*

> ~~Sophie and Florian will prepare a follow-up mail for WP leaders with format and objectives.~~

The respective PEB/PMC will then be used to follow-up on this and refine the agenda with WP leaders.

## Joint EB/CB meeting
The possible joint CB/EB meeting would be on Wednesday afternoon so the boards can have the overview of the work done and roadmap before. Possible topics like "EOSC from a national perspective" or "How to reach users" were discussed.
Follow-up: 
> - agree on topic(s) 
> - find a chair
> - confirm date and availability of the participants

## Announcements
Nicoletta adjusted the promotional messages with final feedback from Patrick & Andy. 
> ~~We may now proceed with the promotion.~~

See previous minutes for dissemination list.
Renata updated the [Indico page](http://indico.eli-beams.eu/e/european_photon_neutron_eosc_symposium) with the last version of the banner and removed the mandatory telephone field for registration.
> Kat and Florian are also finalising the letters to speakers.

## Next meetings
One of the topics for next meeting: how we collect thoughts from registrants.
From now on, the meetings will be held weekly, on Mondays @10am CEST, Kat already set up the Zoom meetings.

**Comment by servansod** [comment]
# 29.09.2020 call
## Dissemination - checked
- XFEL user office, LaseLab, ESFRI, Wayforlight, CalipsoPlus: Florian – DONE
- LENS, PaNOSC partners + twitter + webpage: Nicoletta – DONE
- Light sources communicators, User office Diamond, ExPaNDS partners + twitter + webpage: Kat - DONE
- EOSCsecretariat: Sophie – DONE
- Event will be also communicated in the LightSources newsletter that will be published on 2nd October
- EC/Cordis: announcement is communicated on the Cordis website

Follow-up:
> - LEAPS: Nicoletta has volunteered to distribute the announcement to LEAPS (Ute Krell, Mirjam Van Daalen and Julia Hauk) and Andy will disseminate to LEAPS-IT
> - Patrick to invite ExPaNDS future PO and 5b coordinators

## Registration
So far we have 59 registrants, and out of that 18 has registered only to the first day (Symposium), and 41 has registered to all days.

## Programme for day 2 and day 3
Sophie presented a new structure of these two days. It is anticipated that there will be 9 sessions (each session will last approximately 40 min, 20 min for presentation and 20 min for discussion, with the exception of PaNOSC WP5 who has no sister WP and thus only 30 min), and one 30-minutes wrap-up session at the end. This extends the schedule to 13:00 for both mornings.
Patrick and Andy volunteered to chair/moderate the internal sessions, 1 day each.

Follow up:
>- Renata will update the Indico page to reflect WP day schedule – day 2/3

## Join EB/CB meeting
> - Each project is to send a message to their respective boards to remind them of the upcoming EB/CB meeting and ask if there are subjects they would like to discuss with other projects' facility representatives given the opportunity that everyone will be virtually gathered.

## Letters to speakers
> - Follow up: Kat will send an updated letter to Florian by the end of today (29/09)

## Email to WP leaders
The email has been prepared by Sophie and Florian, and will be updated taking in account the following inputs:
- detail actions in place or foreseen with ESFRI cluster or 5b projects (or any EU-related project),
- think about the report in an user oriented manner,
- better explain we want the complete picture of the collaboration (what both projects do together) and complementarities (what they do separately),
- deadline on 3/11 to upload the presentations and template.

> - Follow up: Sophie/Florian to update and send the mail to WP leaders
> - ~~Nicoletta/Patrick to share a ppt template with PaNOSC and ExPaNDS logos~~

## Next meeting on 5th October
All to think who can moderate 2nd and 3rd session of day 1, and think of questions for the EOSC panel session.

**Comment by JBodera** [comment]
The annual meeting for 2020 was successfully completed and therefore this issue is no longer required.
CLOSED
