### ISSUE TITLE
Review Report: Dissemination plan review

### ISSUE THREAD

**Issue by JBodera** [panosc-eu/panosc#64]
The Review Report reads in section 1.5:
_- Review the Dissemination plan (D9.1). For a long project (48 months) like PaNOSC is necessary that the dissemination plan is an “open document” since the scenario of communication opportunities might change over time (ex. all the onsite activities have been translated to WebRTC channels like Zoom, where the strategy should be redefined; social networks, like twitter, are not used in Zoom environments, so analyzing the new community communication opportunities and shortcomings will be valuable)._

Also, in page 6, section 4.4:
_• Given the PaNOSC commitment with Open Science, open-notebooks etc. it is easy to think that they would publish in Open Access journals as well as they will deposit in a specific green repository (like Zenodo). This issue might be specifically addressed in the reviewed Communication and Dissemination Plan._

Some actions could be:
* Maybe create some timescales for updating the Dissemination Plan (maybe once a year?)

**Comment by NicolettaCarboni** [comment]
Yes, once a year at the end of the year is the best solution

**Comment by NicolettaCarboni** [comment]
PaNOSC communications and dissemination plan has been updated and is available in the CERIC drive only, since the deliverable (and its updates) have been declared as confidential in the GA. The file is now in excel format, to allow easier modification, and includes 5 sheets with all the tables in D9.1:
- PaNOSC external communication and dissemination plan;
- GANTT chart
- Communication tools
- Planned events
- Attended / organized events

**Comment by JBodera** [comment]
D9.1 has been resubmitted
